version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    depends_on:
      - mariadb
    
    volumes:
      - wordpress:/var/www/html
      
    environment:
      - WP_DEBUG=1
    expose:
      - "9000"
    
    networks:
      - inception
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ybarbot/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ybarbot/data/wordpress

networks:
  inception:
    driver: bridge
